version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3003:3003"
    env_file:
      - ./backend/src/.env

  frontend:
    build: ./frontend
    ports:
      - "3002:3002"
    env_file:
      - ./frontend/src/.env
    depends_on:
      - backend
